---
platform: linux

inputs:
  - name: source
  - name: version

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      export VERSION=$(cat version/version)
      make build-all

outputs:
  - name: build
    path: source/build
